export const tagsData = {
  cuisines: [
    "Italian",
    "Chinese",
    "Japanese",
    "French",
    "American",
    "Mexican",
    "Indian",
    "Middle Eastern",
    "Thai",
    "Spanish",
    "Greek",
    "Caribbean",
    "German",
    "Turkish",
    "Korean",
    "Vietnamese",
    "Lebanese",
    "Brazilian",
    "Peruvian",
    "Ethiopian",
  ],
  foodOccasions: [
    "Breakfast",
    "Brunch",
    "Lunch",
    "Dinner",
    "Date Night",
    "Happy Hour",
    "Late Night",
    "Bar Hop",
    "Birthday",
    "Anniversary",
    "Graduation",
    "Wedding",
    "Reunion",
    "Business",
    "Holiday",
    "Game Day",
    "Concert",
    "Wine Tasting",
  ],
  restaurantVibes: [
    "Casual",
    "Fine Dining",
    "Romantic",
    "Sports",
    "Patio",
    "Rooftop",
    "Coffee Shop",
    "Trendy",
    "Brewpub",
    "Family",
    "Outdoor",
    "Rustic",
    "Modern",
    "Elegant",
    "Waterfront",
    "Live Music",
    "Cozy",
    "Upscale",
    "Themed",
    "Vintage",
    "Pop-Up",
  ],
};
