export const tagsData = {
  cuisines: [
    "Italian",
    "Chinese",
    "Mexican",
    "Japanese",
    "Indian",
    "French",
    "Thai",
    "American",
    "Spanish",
    "Greek",
    "Turkish",
    "Korean",
    "British",
    "Vietnamese",
    "Lebanese",
    "Brazilian",
    "Moroccan",
    "German",
    "Argentinian",
    "Peruvian",
    "Pakistani",
    "Malaysian",
    "Ethiopian",
    "Russian",
    "Australian",
    "City Staple"
  ],
  foodOccasions: [
    "Birthday",
    "Anniversary",
    "Late Night Eats",
    "Date Night",
    "Super Hungry",
    "Stay on Diet",
    "Gluten-Free",
    "IYKYK",
    "For Large Groups",
    "Dancing",
    "Happy Hour",
    "Engagement Party",
    "New Years",
    "Graduation",
    "Holidays",
    "Get Work Done",
    "Celebration",
    "Client Dinner",
    "Valentine’s Day",
    "Seasonal",
    "Game Day",
    "Before a Concert",
    "Casual Hangout",
    "New to Town",
    "Entertainment",
    "Pre-Game"
  
  ],
  restaurantVibes: [
    "Casual",
    "Craft Beer House",
    "Social",
    "Games",
    "Family-Friendly",
    "Café",
    "Bistro",
    "Gastropub",
    "Rooftop",
    "Outdoor/Patio",
    "Romantic",
    "Cocktail Bar",
    "Live Music",
    "Speakeasy",
    "Beachfront",
    "Industrial",
    "Rustic",
    "Lounge",
    "Steakhouse",
    "Buffet",
    "Farm-to-Table",
    "Modern",
    "Sports Bar",
    "Bar",
    "Diner",
    "Winery"
  ],
};
