export const tagsData = {
  cuisines: [
    "Italian",
    "Chinese",
    "Mexican",
    "Japanese",
    "American",
    "Indian",
    "French",
    "Mediterranean",
    "Thai",
    "Spanish",
    "Middle Eastern",
    "Greek",
    "Korean",
    "Lebanese",
    "Turkish",
    "Vietnamese",
    "Caribbean",
    "Brazilian",
    "Argentinian",
    "Moroccan",
    "Pakistani",
    "German",
    "Peruvian",
    "Malaysian",
    "Ethiopian",
    "Cuban",
    "Russian",
    "British",
    "Australian",
  ],
  foodOccasions: [
    "Breakfast",
    "Lunch",
    "Dinner",
    "Brunch",
    "Birthday",
    "Anniversary",
    "Date Night",
    "Super Hungry",
    "Stay on Diet",
    "Gluten-Free",
    "IYKYK",
    "For Large Groups",
    "Dancing",
    "Happy Hour",
    "Late Night Eats",
    "Engagement Party",
    "New Years",
    "Graduation",
    "Holidays",
    "Thanksgiving",
    "Christmas",
    "Easter",
    "Halloween",
    "Get Work Done",
    "Celebration",
    "Client Dinner",
    "Valentine’s Day",
    "Seasonal",
    "Game Day",
    "Before a Concert",
    "Casual Hangout",
    "New to Town",
    "Entertainment",
    "Pre-Game"
  ],
  restaurantVibes: [
    "Casual",
    "Family-Friendly",
    "Bistro",
    "Café",
    "Social",
    "Outdoor/Patio",
    "Bar",
    "Craft Beer House",
    "Gastropub",
    "Sports Bar",
    "Dive Bar",
    "Diner",
    "Buffet",
    "Lounge",
    "Cocktail Bar",
    "Rooftop",
    "Live Music",
    "Romantic",
    "Speakeasy",
    "Farm-to-Table",
    "Winery",
    "Steakhouse",
    "Beachfront",
    "City Staple",
    "Rustic",
    "Modern",
    "Industrial",
    "Upscale",
    "Games"
  ]
};
